version: '3.8'
services:
    db:
        image: 'mysql:latest'
        environment:
            - MYSQL_ROOT_PASSWORD=MYSQL_RANDOM_ROOT_PASSWORD
            - MYSQL_USER=demo
            - MYSQL_PASSWORD=jEYgQBtEqeCZ107
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/databases-backup.sql
        networks:
            - demo_app
    php:
        container_name: php
        build:
            context: ./docker/php
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - demo_app
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - db
        networks:
            - demo_app
volumes:
    mysql-data:
networks:
    demo_app: